### ISSUE TITLE
[FxA settings] Tab name is incorrect on Chrome when using Spanish

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#12558]
**Affected platforms:**

* Chrome browser;

**Affected FxA versions:**

* Stage: 1.230.3;
* Production: 1.229.1

**Prerequisites:**

* Have a FxA account 

**Steps to reproduce:**

1. Log into the FxA account, either on Stage or **Production** while the browser language is English;
1. Open browser settings and change the language to Spanish;
1. Refresh the FxA settings page and take a look at the tab name;

**Expected result:**

* The tab name is Firefox Accounts;

**Actual result:**

* The tab name is {-product-firefox-accounts} ;

Please see more in the attached video.

**Additional notes:**

Same issue occurs on Firefox browser. 

Bento menu is also affected. Please see screenshot:

!es - product name issue.png|width=226,height=367!

┆Issue is synchronized with this [Jira Bug](https://mozilla-hub.atlassian.net/browse/FXA-4906)
┆Attachments: <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/22956">2022-04-19_12h09_46.mp4</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/23350">es - product name issue.png</a> | <a href="https://mozilla-hub.atlassian.net/rest/api/2/attachment/content/24128">image-20220523-123351.png</a>

**Comment by LZoog** [comment]
_Originally posted by @peiying2 in https://github.com/mozilla/fxa/issues/12669#issuecomment-1111300590_

> > @peiying2 Can you think of why some placeables might not get copied over correctly? I was checking out #12558 which I know we were pinging about in Slack, but it looks like some of those placeables are just completely [missing from `es`](https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/es/settings.ftl) and I wonder if that's the case in other locales.
> 
> The completion of `es` is very low compared to other `es-*` flavors.
> 
> I also noticed that some of the `##` line items are empty in the templates: https://github.com/mozilla/fxa-content-server-l10n/blob/6d13a17cd5d626c920203aaf18b00848e8cb0af6/locale/templates/settings.ftl#L315. And you can spot quite a few of them in the file.

I think the problem with this is that many of the placeables aren't present at all though, not that the completion is low. Users are seeing `{-product-firefox-accounts}` because it's not in that file. Looks like we're seeing that in #12691 too, missing `⁨{-brand-name-firefox}⁩`, however it's in [our template file](https://github.com/mozilla/fxa-content-server-l10n/blob/master/locale/templates/settings.ftl). We could get a PR up to fix that, but I'm wondering if that could be happening in other locale files because it feels like that's a Pontoon sync related thing which makes me think a PR from our side might be a bandaid and not fix the problem in the future?

**Comment by flodolo** [comment]
This should have been fixed by https://github.com/mozilla/fxa-content-server-l10n/pull/597 for `es`

**Comment by data-sync-user** [comment]
➤ Luminita Buruian commented:

Francesco Lodolo We have checked this today  on the Satging version 1.232.5 and th eissue still reproduces.

Has this been deployed to staging yet?

Thank you.

!image-20220523-123351.png|width=995,height=276!

**Comment by data-sync-user** [comment]
➤ Francesco Lodolo commented:

That is really a question for the FxA team, as I don’t know the mechanics for deployment (stage or prod). 

It’s fixed in the l10n repo, that’s the only thing I’m sure of.
