### ISSUE TITLE
Server error when destroying a stage account with fxacli

### ISSUE THREAD

**Issue by isabelrios** [mozilla/fxa#1740]
As part of our [Sync Integration iOS tests](https://github.com/mozilla-mobile/firefox-ios/tree/master/SyncIntegrationTests), we use an stage account created with `fxacli` tool, after each test the account is destroyed,

Since July the 10th we are seeing this error: `fxa.errors.ServerError: An internal server error occurred` when running the command to destroy the account `fxacli destroy --email .... --password .....`

**Comment by philbooth** [comment]
Wondering if I might have caused this inadvertently with #1671.

**Comment by philbooth** [comment]
Fixed in 141.3, which is now on stage.

**Comment by isabelrios** [comment]
@philbooth sorry for asking, I'm not familiar with this processes...how long does it take to be solved on production? Just wondering because we still see the failure and would like to now about the timing to disable the tests in the meantime or wait until the fix. Thanks!

**Comment by philbooth** [comment]
It's in production already, so I'll re-open this.

**Comment by dannycoates** [comment]
update: I'm able to reproduce this with fxacli on prod and stage but not stable, latest, or even locally using the same commit from production so this is basically impossible for me to debug. It doesn't seem to be a simple code issue, config maybe? I'll check the stage server logs as soon as I can get to them.

**Comment by philbooth** [comment]
> It doesn't seem to be a simple code issue, config maybe?

Could be, although the timing of the initial report makes it seem like something I introduced in #1671. Or if not that, the refactoring that preceeded it in #1685.

**Comment by isabelrios** [comment]
In our case this issue is 100% reproducible. We create and verify the account, then sign in desktop and firefox-iOS, then it is removed. I don't know how I could help but please let me know if I can share some logs or info if that helps you to debug this. 
Thanks!

**Comment by dannycoates** [comment]
`subhub.deleteCustomer.failed`

**Comment by dannycoates** [comment]
So, on stage this is failing because of `subhub.deleteCustomer.failed` but prod is probably a different story. still looking

**Comment by dannycoates** [comment]
somehow this works against prod now. From the query I had jrgm run on the prod logs the most likely cause was `request timed out  customs.check.1`.  I don't even know how to follow up from here 🤷‍♂️

**Comment by eoger** [comment]
We're seeing the same problem on `stage` currently in our sync integration tests: https://circleci.com/gh/mozilla/application-services/40830

**Comment by rfk** [comment]
I re-opened this but then realized there was already an open bug at https://github.com/mozilla/fxa/issues/3629
