### ISSUE TITLE
Broken links in Firefox Privacy Notice page

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#3368]
**Notes:**
This is a follow-up issue for #2777

**Build:**
Stage [Train 1.150.2]

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**
1. Go to https://accounts.firefox.com/legal/privacy
2. Click on the following links
a) “Android” https://firefox-source-docs.mozilla.org/mobile/android/fennec/index.html
b) “documentation” https://firefox-source-docs.mozilla.org/mobile/android/fennec/adjust.html
c) “Android” https://firefox-source-docs.mozilla.org/mobile/android/fennec/mma.html

**Expected results:**
All pages are successfully displayed.

**Actual Results:**
404 Not Found is returned.

![android1](https://user-images.githubusercontent.com/18114210/68851011-bb694980-06dd-11ea-8ac4-789c6ae6ebc0.png)
![documentation](https://user-images.githubusercontent.com/18114210/68851016-c02dfd80-06dd-11ea-9e53-a31ae5a3c3a2.png)
![android2](https://user-images.githubusercontent.com/18114210/68851023-c328ee00-06dd-11ea-9378-d4e06f1c5bb6.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-1015)
┆Issue Number: FXA-1015

**Comment by clouserw** [comment]
This isn't live yet, so the step 1 should be using https://accounts.stage.mozaws.net/legal/privacy .  That said, it does seem like they are still broken there.  @mozilla/fxa-devs can y'all confirm how legal docs are put on the site?  https://mozilla.github.io/ecosystem-platform/docs/fxa-engineering/fxa-localization says "During the FxA docker image build, the head of the legal-docs repo is pulled in and the markdown documents converted to HTML."

**Comment by clouserw** [comment]
Actually, I don't think this is us.  The links on the other site are broken again.  I'll ask them to update.  Sorry for the ping everyone!

**Comment by clouserw** [comment]
Ok.  This is fixed in the legal-docs repository.  During a push the latest copy of the legal-docs are pulled down and deployed, so, this should go out next time we deploy.  Thanks.

**Comment by vasilicatamas** [comment]
The links mentioned in description are still broken in Prod [1.151.2]. Any thought @clouserw ?

**Comment by clouserw** [comment]
I see that too.  They aren't being updated, but I need help to figure out why.

I'm expecting [this page](https://accounts.firefox.com/legal/privacy) to have [this content](https://github.com/mozilla/legal-docs/blob/master/firefox_privacy_notice/en-US.md).

It looks like grunt does something with it in [yeoman.js](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/grunttasks/yeoman.js) and [replace.js](https://github.com/mozilla/fxa/blob/master/packages/fxa-content-server/grunttasks/replace.js) but I don't know much about how those are called.

After checking [our version endpoint](https://accounts.firefox.com/__version__) it looks like our legal docs were last updated on Nov 11.

**Comment by clouserw** [comment]
The circleci logs might have some help here

**Comment by vasilicatamas** [comment]
Seems that all 3 broken links have been updated in https://accounts.stage.mozaws.net/legal/privacy. Tested on Stage [1.152.0] under Windows 10 64-bit. 
1. https://firefox-source-docs.mozilla.org/mobile/android/index.html
2. https://firefox-source-docs.mozilla.org/mobile/android/adjust.html
3. https://firefox-source-docs.mozilla.org/mobile/android/mma.html

**Comment by clouserw** [comment]
Looks like stage got updated to HEAD.  Prod hasn't yet, but we haven't pushed.  @vbudhram did you do anything here?  I didn't

**Comment by vbudhram** [comment]
I haven't pushed anything but looks like they are running different TOS commits so this might get fixed when prod is updated?

https://accounts.stage.mozaws.net/__version__
https://accounts.firefox.com/__version__

**Comment by clouserw** [comment]
Yeah, that's how it's supposed to work, but it hasn't been since November.  Anyway.... I guess this is fixed.  We can keep an eye on it.  Thanks.

**Comment by vasilicatamas** [comment]
These links seem to be broken again - both prod (https://accounts.firefox.com/legal/privacy) and stage (https://accounts.stage.mozaws.net/legal/privacy)

![broken links](https://user-images.githubusercontent.com/18114210/73634901-ee7f0180-466a-11ea-91d6-30a5df0e36ba.gif)

**Comment by clouserw** [comment]
Closing in favor of https://jira.mozilla.com/browse/FXA-1023
