### ISSUE TITLE
Mozilla VPN icon is missing in the “Thanks!” resubscribe popup

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/fxa#5952]
#### Affected versions:
- All Firefox;

#### Affected FxA versions:
- 1.179.3;

#### Affected Platforms:
- Windows 10 (64-bit);

#### Prerequisites:
- have an FxA account with active subscription;

#### Steps to reproduce:
1. Go to manage subscription page -https://payments-stage.fxa.nonprod.cloudops.mozgcp.net/subscriptions using the account from prerequisites;
2. Cancel Mozilla VPN subscription;
3. Click the “Resubscribe” button and finalize resubscription;
4. Observe “Thanks!” for resubscribing popup;

#### Expected result:
- Mozilla VPN product icon is displayed above the thank-you message.

#### Actual result:
- Mozilla VPN product icon is NOT displayed above the thank-you message.
![iconmissing](https://user-images.githubusercontent.com/15685960/87529423-a6dbb780-c697-11ea-9660-ec5b9806d9b7.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2291)
┆Issue Number: FXA-2291

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

[~jgruen@mozilla.com] said this was fixed on Slack

**Comment by ValentinaPC** [comment]
> 
> 
> ➤ Wil Clouser commented:
> 
> [~[jgruen@mozilla.com](mailto:jgruen@mozilla.com)] said this was fixed on Slack

Verified this on Stage 179.4, Fx 78.02, Win 10, and the issue is still reproducing. Also observed, that the icon is there, but it is white.
Please see below video.
![hideands](https://user-images.githubusercontent.com/15685960/87665981-7e73bc00-c770-11ea-9703-9ba1c634d31f.gif)

**Comment by data-sync-user** [comment]
➤ John Gruen commented:

So the Icon is there, but it's all white...i think this gets fixed by adding a color background or something 🙁

**Comment by ValentinaPC** [comment]
Verified as fixed in stage, using Fx78.0.2 and Windows 10 (64-bit).
Postfix screenshots below.
![image](https://user-images.githubusercontent.com/15685960/88532250-ed70d080-d00c-11ea-9e0f-12970ae5445a.png)
![image](https://user-images.githubusercontent.com/15685960/88532225-e21da500-d00c-11ea-871f-766903be8450.png)
