### ISSUE TITLE
[FxA-Settings] The avatar icon disappears from header and Picture section on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6359]
**Build**
Stage [Train 1.186.0]

**Affected platforms**
iOS 13.6 

**Affected devices**
iPhone 11

**Steps to reproduce**
1. Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2. Open the avatar drop-down.
3. Close the avatar drop-down.
4. Scroll down.

**Expected results**
All the avatar icons are displayed without issues.

**Actual Results**
The avatar icons disappear.

![issue6](https://user-images.githubusercontent.com/18114210/92005211-dfb91400-ed4b-11ea-8fc2-f8e091b4739b.gif)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2507)
┆Issue Number: FXA-2507

**Comment by jodyheavener** [comment]
I believe this is fixed in #6350 and should be verifiable in the next train.

**Comment by vasilicatamas** [comment]
This issue still reproduces on Stage [Train 1.192.0] under iOS 13.6. Reopening.

![issue20](https://user-images.githubusercontent.com/18114210/97303111-a3dd8f00-1862-11eb-840b-5db7c1772167.gif)

**Comment by data-sync-user** [comment]
➤ Danny Coates commented:

oh! this is on firefox not safari

**Comment by vasilicatamas** [comment]
This issue was verified as fixed on Stage [Train 1.193.0] under iOS 13.6. The avatar icon from header and Picture section are correctly displayed.

![issue37](https://user-images.githubusercontent.com/18114210/98665606-95a86c00-2354-11eb-9a69-7e13fd4df4a8.gif)
