### ISSUE TITLE
Unexpected error received while deleting a Firefox account

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#6606]
**Build**
Stage [Train 1.190.1]

**Affected platforms**
Windows 10 x64 

**Steps to reproduce**
1. Login using an existing account.
2. Navigate to Manage Account page.
3. Click Delete button from the “Delete account” area.
4. Type the correct password and check the checkboxes.
5. Click “Delete account”.

**Expected results**
The account is successfully deleted.

**Actual Results**
“Unexpected error” appears and the account is not deleted: “Unexpected error”.

![Screenshot_11](https://user-images.githubusercontent.com/18114210/95069500-7132f180-070f-11eb-96c0-703f0529dab2.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-2592)
┆Issue Number: FXA-2592

**Comment by LZoog** [comment]
Oooh, not certain this is what's happening but this could be related to an issue where if this account previously signed up for a subscription through Stripe and then the account was deleted and remade, the account can't be deleted because there's a discrepancy between the UID I believe of the account in FxA and Stripe.

I've only reproduced this locally though by creating an account, signing up for a subscription successfully, restarting all the servers, remaking the account, and trying to delete the account.

**Comment by jbuck** [comment]
This is resolved now, needed to add config for the auth server

**Comment by vasilicatamas** [comment]
This issue still reproduces on stage Train 1.190.1 but is not encountered on production Train 1.190.1.

**Comment by clouserw** [comment]
@jbuck is stage missing a config that prod has?

**Comment by jbuck** [comment]
> @jbuck is stage missing a config that prod has?

I think the culprit was me changing mysql permissions while the instance was connected to the database, based on my reading of https://dev.mysql.com/doc/mysql-security-excerpt/5.6/en/privilege-changes.html

I terminated the instance and the new one is working correctly according to some failing kintowe tests reported by @smarnach

**Comment by vasilicatamas** [comment]
Confirm that the account is successfully deleted and the error is no longer encountered on Stage [Tran 1.191.1] . 

![issue18](https://user-images.githubusercontent.com/18114210/95741043-3c3a1800-0c96-11eb-9e86-37a9649a5862.gif)
