### ISSUE TITLE
[FxA-Settings] Close button from new 2FA codes screen is incorrectly displayed

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/fxa#7028]
**Build**
Stage [Train 1.194.0]

**Affected platforms**
Windows 10
Android 9
iOS

**Steps to reproduce**
1.Navigate to https://accounts.stage.mozaws.net/beta/settings/ and login using an existing account.
2.Click on the "Change" button displayed in the "Two-step authentication" section.
3.Click on "Change codes" button.
4.Check the “Close” button.

**Expected results**
“Close” button extends to the entire page content width - as "Close" button from Recovery key page

![Screenshot_54](https://user-images.githubusercontent.com/18114210/100458992-5ce6f180-30cd-11eb-8a1c-53382445605a.png)

**Actual Results**
“Close” button is smaller than the page content width.

![Screenshot_53](https://user-images.githubusercontent.com/18114210/100458988-5bb5c480-30cd-11eb-8f6c-b0d6df5ea852.png)

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-2757)
┆Issue Number: FXA-2757

**Comment by Cronus1007** [comment]
@clouserw  Let me take a look at the issue.

**Comment by Cronus1007** [comment]
@clouserw  @vasilicatamas would be a great help if you refer the `apis` ensured for checking the `platforms` in the code.

**Comment by saurabh-jaiswal-333** [comment]
Hi, @clouserw  I have reproduced this issue and can see that the close button does not extend the whole width. I am a beginner in the open-source community and would like to work on this issue.

**Comment by Cronus1007** [comment]
@saurabh-jaiswal-333  I am already on this issue.

**Comment by hitesh-coder** [comment]
@clouserw if this issue still exists i would like to work on it

**Comment by patil2097** [comment]
Hi @clouserw , I would love to help in closing this issue. Can you let me know the location of the file. Would be really helpful.

**Comment by Cronus1007** [comment]
@patil2097

**Comment by LZoog** [comment]
Hey @saurabh-jaiswal-333 @Cronus1007 @hitesh-coder @patil2097, sorry for not getting back to you!

This issue was resolved in another pull request so I'm going to close it. There is a related issue, #8010, but it's a little more involved than a quick CSS tweak. Please feel free to look at our other `good first issue`s too. Thanks! :)

**Comment by data-sync-user** [comment]
➤ Vasilica Tamas commented:

Hi [~lzugai@mozilla.com]. I just checked and this issue is still reproducible in Stage [Train 1.204.3] under Windows 10 64-bot, Android 9 and iOS 14.4. The "Close" button it's still not extended to the entire page content width.
