### ISSUE TITLE
[FXA-Settings] Inconsistent casing – should be sentence case

### ISSUE THREAD

**Issue by janiceahn** [mozilla/fxa#7758]
## Description

Inconsistent casing across page. Some examples:

Subcategory titles: "Primary email" and "Secondary Email"
Subcategory status: "Not set" and "Not Set"
Buttons: "Delete Account"
Connected services status: "a day ago"
Stepped page headers: "Two-Step Authentication"

**Non-exhaustive—site should be scraped**

### Steps to reproduce

![image](https://user-images.githubusercontent.com/6219141/110508127-b13b3d80-80ce-11eb-91f6-e2b073197074.png)

![image](https://user-images.githubusercontent.com/6219141/110508152-b7c9b500-80ce-11eb-8960-7dfe49e7024d.png)

<img width="271" alt="Untitled 2" src="https://user-images.githubusercontent.com/6219141/110508731-51916200-80cf-11eb-9a40-752f4e8b1b91.png">

![image](https://user-images.githubusercontent.com/6219141/110514277-23af1c00-80d5-11eb-9ef0-8a5adef4f7ae.png)

<img width="574" alt="Untitled 3" src="https://user-images.githubusercontent.com/6219141/110516463-9ae5af80-80d7-11eb-8599-b4e6f813b021.png">

### Expected result

Sentence case (not camel case, not all lowercase).

<img width="235" alt="Untitled 6" src="https://user-images.githubusercontent.com/6219141/110508274-d9c33780-80ce-11eb-84cb-c9eaa375dba5.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/FXA-3155)
┆Issue Number: FXA-3155

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

These shouldn't need new strings as it's just changing case.

**Comment by Yogita98** [comment]
We don't have to explicitly change any of the strings here right? So, a function to convert all the strings to title case would work @janiceahn?

**Comment by janiceahn** [comment]
@Yogita98 Yes, that would work. Thank you!

**Comment by Yogita98** [comment]
Hey @janiceahn recently I pulled in new changes from `main` and the issue seems to have been fixed already. Can you please confirm the same?

**Comment by LZoog** [comment]
@Yogita98 I'm also seeing these as fixed. I will go ahead and close this issue - thank you for looking into this for us! :)

**Comment by LZoog** [comment]
Actually @Yogita98... I just realized I'm still seeing "Secondary Email" when I _don't_ have a secondary email:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/13018240/112685178-339f5d80-8e42-11eb-954d-005af8905378.png">

We shouldn't need a function to fix this up for us though. I briefly looked into this and at a first glance I'm not sure why this is happening, in `UnitRowSecondaryEmail.tsx` we're passing in "Secondary email", our localization file also has "email" lowercased, and there's not any CSS causing this. Please feel free to take a look further if you'd like!

**Comment by Yogita98** [comment]
@LZoog sure I'd like to give it a shot!

**Comment by Yogita98** [comment]
I pulled in new changes before giving it a shot and it took me a while to solve the errors after pulling in new changes. When I was finally able to start all the services, I observed that the issue had been fixed already. Can you confirm the same?

**Comment by LZoog** [comment]
@Yogita98 Well... you seem to be right! That's what I get for checking out staging instead of running the latest locally and double checking. Thanks for looking into it again. 😆

<img width="596" alt="image" src="https://user-images.githubusercontent.com/13018240/113013494-5f239000-9141-11eb-85ef-ab3bdd400193.png">

Closing this as this should no longer be an issue on the next push to staging.
