### ISSUE TITLE
[FxA-Settings] ‘Profile picture’, ‘Change password’ and ‘Two-step authentication’ separate pages title is written with uppercase letters

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#7919]
**Build:**
 Stage [Train 1.202.3]

**Affected platforms:**
 Windows 10
 Android 8

**Steps to reproduce:**

1. Navigate to [https://accounts.stage.mozaws.net/](https://accounts.stage.mozaws.net/) and log in using an existing account.
1. Click on the ‘Add’/ ‘Change’ button in the Picture section and observe the title of the page.

**Actual result:** 
 The second word of the page’s title is written with uppercase letters.

**Expected result:** 
 The second word of the page’s title is written with lowercase letters.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3231)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15581/Separate+page+-+title+with+uppercase.PNG">Separate page - title with uppercase.PNG</a> | <a href="https://jira.mozilla.com/secure/attachment/15580/Separate+page+-+title+with+uppercase2.PNG">Separate page - title with uppercase2.PNG</a>
┆Issue Number: FXA-3231

**Comment by vbudhram** [comment]
Tested locally and looks like these are all fixed in current train.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Did this bug miss the 203 Train? Because it is still reproducible on Stage [Train 1.203.5] and Production [Train 1.203.4] on Windows 10 x64 and Android 11.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

The issue is still reproducible on Stage [Train 1.207.0] on Windows 10 x64, Android 11, iOS 14.4 and macOS 10.14. Reopening.
