### ISSUE TITLE
[FxA-Settings] Text overlaps when the browser's language is set to German

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/fxa#8256]
**Build:**
Stage [Train 1.203.7]

**Affected platforms:**
Windows 10 x64

**Preconditions:**
The browser's language is set to German.

**Steps to reproduce:**

1. Navigate to https://accounts.stage.mozaws.net/settings and log in using an existing account.
1. Go to Security section and observe the Recovery key title and status.

**Actual result:** 
The title overlaps the status text.

**Expected result:** 
The title and the status text are correctly displayed.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/FXA-3365)
┆Attachments: <a href="https://jira.mozilla.com/secure/attachment/15971/Settings+page+-+text+overlaps+in+Deutsch.PNG">Settings page - text overlaps in Deutsch.PNG</a>
┆Issue Number: FXA-3365

**Comment by data-sync-user** [comment]
➤ Wil Clouser commented:

Lets set this to break in CSS

**Comment by clouserw** [comment]
@peiying2 just FYI

**Comment by peiying2** [comment]
This could be an i18n issue. The field needs to be limited to certain size so it doesn't cross the "isle" to the other column, and allows wrapping. I wonder what happens with French and Spanish, which have longer text, but  made up with multiple words.

**Comment by clouserw** [comment]
We're planning on forcing a break at the edge of that column.  If a language has word breaks it'll wrap to the next line already.

**Comment by peiying2** [comment]
I can ping the localizer to see if there is a natural break, like hyphenated. Not  sure our system knows where a "good" break should be.

**Comment by clouserw** [comment]
It wouldn't know - it would just chop it off wherever it hit the border.  If it's possible to shorten the string in German that would be ideal.  Thanks for pinging them.

**Comment by peiying2** [comment]
@clouserw the suggestion on the hyphenation is `Wiederherstellungs-schlüssel`. Is it short enough?

**Comment by clouserw** [comment]
There is a screenshot in Jira: 
![image](https://user-images.githubusercontent.com/80098/114900364-a6a84e00-9dc8-11eb-8e07-b952ca8a453f.png)

Based on that, it looks like your proposal would fix this issue

**Comment by peiying2** [comment]
> There is a screenshot in Jira:
> ![image](https://user-images.githubusercontent.com/80098/114900364-a6a84e00-9dc8-11eb-8e07-b952ca8a453f.png)
> 
> Based on that, it looks like your proposal would fix this issue

He only proposed it but didn't make any changes in Pontoon. I can do it if it  is not too late to make the change for the next code push.

**Comment by peiying2** [comment]
OK, I fixed it in Pontoon. Let's see if this will do the trick. Basically the gap between the two columns have to be pretty narrow to accommodate the change.

**Comment by clouserw** [comment]
Great, thank you.

We just deployed stage this morning, so, this will go live on there if we do a dot release, or else would be in production on Apr 21.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Did this bug miss the Train 205? Because it is still reproducible on Stage [1.205.0] on Windows 10 x64.

**Comment by data-sync-user** [comment]
➤ Bianca Oltean commented:

Retested the issue on Stage [1.207.0] under Windows 10 and it is still reproducible.
[~wclouser@mozilla.com] Did this bug miss the Train?
